# Generated by Django 5.1 on 2024-10-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='tareas', to='taskmaster.etiqueta'),
        ),
    ]
